### PR TITLE
Change iOS Deployment Target to iOS 8

### PR DESCRIPTION
**Pull request by CodeEagle**

### CODE REVIEW

**Comment by CodeEagle** [comment]
I signed it!

**Comment by shoumikhin** [comment]
Hi @CodeEagle,

So, iOS deployment target currently isn't specified at all. What kind of issues do you experience and why does it seem important to specify the version explicitly?

**Comment by CodeEagle** [comment]
It's using latest version of iOS.
I compile it and use in project, it requires iOS 11.2...

**Comment by shoumikhin** [comment]
Alright, hope you get that resolved.
I'll follow up with further explicit deployment targets in a sec.

**Pull request merged**
