### PR TITLE
Bump version to 1.2.9.

### PR DESCRIPTION
**Pull request by ykjchen**

### CODE REVIEW

**Comment by ykjchen** [comment]
@tristane0 @shoumikhin Does this look complete?

**Comment by shoumikhin** [comment]
Love it!

**Comment by tristane0** [comment]
Looks good, thank you!

We also reference the latest release here: https://github.com/google/promises/blob/master/g3doc/index.md

But maybe we could generalize that reference so that we don’t have to update that file for each new release?

**Comment by ykjchen** [comment]
Good idea, updated docs to reference latest minor version.

**Comment by ykjchen** [comment]
FYI encountered some errors during pod lib lint, still need to resolve before tagging and pushing to trunk.

**Comment by sushichop** [comment]
@ykjchen 

I investigated pod lib lint error.
I think #145 and #148 needs be merged to fix pod lib lint error about `PromisesObjC.podspec` at least.

Could you see that?
Then try `pod lib lint PromisesObjC.podspec` 

Thanks in advance.

**Comment by ykjchen** [comment]
@shoumikhin @tristane0 I'm trying to push to trunk and seeing:

```
... are not allowed to push new versions for this pod. The owners of this pod are ...
```

Are either of you able to add me as an owner?

```
pod trunk add-owner ...
```
https://guides.cocoapods.org/making/getting-setup-with-trunk.html

**Pull request merged**
