### PR TITLE
Updated to Swift 4.2

### PR DESCRIPTION
**Pull request by alexanderkhitev**

### CODE REVIEW

**Comment by alexanderkhitev** [comment]
I signed it!

**Comment by alexanderkhitev** [comment]
@shoumikhin Yes, I tested the launch of tests in Xcode Version 9.4.1, all tests are successful.
I also looked in the settings for Xcode Version 9.4.1 to set Swift 4.1 as the default in this case. 
https://monosnap.com/file/z7QpilHT7HtHYeIEvW4cAeMsw1cPv7

**Comment by temrich** [comment]
Hey Alexander, thank you for the PR! Any specific reason why we should update the default Swift version from 4.0 to 4.2 at this time? Are you running into any issues in Xcode 10 with Swift 4.2?
Thank you!

**Comment by alexanderkhitev** [comment]
Hey @temrich ! I ran the project on Xcode 10 and there it was indicated to update the project to Swift 4.2 in several pods. When I updated all pods and did prs, only the Promises framework was left, but this warning is easy to fix if I write `config.build_settings ['SWIFT_VERSION'] = '4.2'` or the path to my fork in the Podfile. I just decided to do PR to fix this warning without any additional action. Thanks for the framework, everything works fine.

**Comment by temrich** [comment]
Thank you for the quick reply! That makes sense.

Do you know if developers who still use 9.4.1 or lower (which I imagine is quite a few still) will see a warning if the targeted Swift version is updated to 4.2? Am wondering if we should hold off on this PR for a bit until more developers switch over to Xcode 10 and Swift 4.2?

**Comment by alexanderkhitev** [comment]
@temrich 
Among my friends, all the guys switched to Xcode 10 and Swift 4.2, of course I know that some frameworks (I can give an example), have not yet switched to Xcode 10 and Swift 4.2 and of course you can wait some more time.

**Comment by wangjiejacques** [comment]
@temrich for those who use Xcode 9.4.1, they can use the previous version, both Cocoapod and Cathage support specific version. I think it's OK to merge this pull request.

**Comment by ssg** [comment]
When is this going to be out?

**Comment by shoumikhin** [comment]
Just to clarify, what’s the main concern with not updating the Swift version now? Is that the Xcode suggestion that pops up every time you regenerate the project with CocoaPods? What other difficulties do you guys face with Promises now upgrading the Swift version?

**Comment by soucolline** [comment]
What's the main concern not to update ? Whomever did not upgrade to Xcode 10 / swift 4.2 can target `1.2.4`, and the rest can get rid of this very annoying warning

**Comment by shali3** [comment]
+1

**Comment by temrich** [comment]
Hey Alexander, thank you for the PR and sorry for the delayed reply. We are working on updating Travis to Xcode 10 and updating the Swift version from 4.0 to 4.2 in [PR93](https://github.com/google/promises/pull/93). Would like to keep the Xcode and Swift version updates in the same PR.

Thank you!

**Pull request closed without merging**
