### PR TITLE
Fix SwiftUI previews crashes when Promises is statically linked.

### PR DESCRIPTION
**Pull request by ykjchen**
Targets #189 by applying the fix suggested in https://github.com/google/promises/issues/189#issue-1275085478

### CODE REVIEW

**Comment by ykjchen** [comment]
@paulb777 could you PTAL? Thanks!

**Comment by ykjchen** [comment]
I assumed the +Testing category doesn't need to be included. Please let me know if it does.

**Comment by chuckhays** [comment]
LGTM

**Comment by paulb777** [comment]
Our testing is showing an issue. It may be related to not including `+Testing`. We'll verify and let you know.

**Pull request merged**
