### PR TITLE
Update docs about all(...) rejection logic

### PR DESCRIPTION
**Pull request by shali3**
I added this since it is not clear from the docs what happens in case of failure.

### CODE REVIEW

**Comment by shali3** [comment]
I signed it!

**Comment by shoumikhin** [comment]
Hi ShaLi,

Thank you for the PR!

Where does that error come from? Could you try upgrading your bazel version to 0.20 and applying the following [patch](https://github.com/shoumikhin/promises/commit/26211934115314b279bb393c5ab7af8fb8da250d)?

Thanks.

**Comment by shali3** [comment]
Done

**Comment by temrich** [comment]
Thank you, ShaLi, for the PR. Really appreciate it!

**Pull request merged**
