### PR TITLE
Swift 5

### LINKED ISSUE #104: Update to Swift 5
As Swift 5 now is released is there any plan to merge the code to Swift 5?

### PR DESCRIPTION
**Pull request by kimdv**
Resolved #104

### CODE REVIEW

**Comment by shoumikhin** [comment]
Thanks!
We'll merge this once we confirm it's safe to do so.

**Comment by WyattMufson** [comment]
@shoumikhin any idea when this will be merged in?

**Comment by shoumikhin** [comment]
Hi Wyatt,

Typically, it takes about 2 weeks to make a new major Xcode release adopted across Google’s infrastructure. Then we need to make sure all the apps built with Promises and Swift 5 work as expected. But the process may move faster or slower, I cannot really predict the exact timing.

Are you somehow blocked on us not switching to 5 immediately? Doesn’t seem there’re any code changes, perhaps you could patch this PR with version upgrade locally at the moment if that’s important for you to move forward?

Thanks.

**Comment by WyattMufson** [comment]
@shoumikhin no worries at all. Not blocked at all, was just curious. Thanks for the detailed explanation, appreciate it.

**Comment by temrich** [comment]
We are still looking to update to Swift 5 as soon as possible; however, there's a Bazel [issue](https://github.com/bazelbuild/bazel/pull/7830) with Xcode 10.2 that's blocking the update. It appears the issue should be resolved in Bazel 0.25.0.

**Comment by kimdv** [comment]
Thanks a lot @temrich ! 🚀

**Comment by temrich** [comment]
@kimdv I've updated Travis to Bazel 0.25 and Xcode 10.2 and the build passes. So you should be good to update this PR and rerun the Travis build. Thank you for your help with migrating to Swift 5!

**Comment by kimdv** [comment]
@temrich rebased and pushed ✅

**Comment by temrich** [comment]
Thank you!

**Pull request merged**
