### PR TITLE
Change Promise properties: isPending, isFulfilled, isRejected from In…

### PR DESCRIPTION
**Pull request by oxview**
Change Promise properties: `isPending, isFulfilled, isRejected` from **Internal** to **Public**

### CODE REVIEW

**Comment by shoumikhin** [comment]
Hi @oxview, could you provide any more info on why you believe exposing those properties is necessary?

**Comment by oxview** [comment]
@shoumikhin Moving from other ```Promises``` someone throw exception if promise is already NOT in pending state and you try to fulfill or reject it, in ```google/promises``` it will be ignored, I understand that doing this now will break API, but because human factor are not excluded throwing exception on fulfill/reject if not in pending state sometime help to prevent wrong logic (helpful for beginners), but this is just a suggestion.

**Comment by shoumikhin** [comment]
Thanks you for the details!

Are you using some kind of a networking library that provides a delegate to notify about connections? Wonder if there's any API which provides a completion handler instead, which you could then wrap with [`resolve`](https://github.com/google/promises/blob/master/g3doc/index.md#resolve)?

If no, and being a delegate is the only way, how about a nullable `Promise`?

```swift
var promise: Promise<Void>?

func connect() -> Promise<Void> {
    if promise != nil {
        promise?.reject(MyError.abandoned)
        promise = nil
    }
    let newPromise = Promise<Void>.pending()
    promise = newPromise

    // connect to host ...
    
    return newPromise
}

func socket(didConnectToHost host: String) {
    promise?.fulfill(())
    promise = nil
}

func socket(didDisconnectFromHost host: String) {
    if promise != nil {
        promise?.reject(MyError.disconnected)
        promise = nil

        // we are sure that we was not connected, self.promise was not fullfiled/rejected
        // do 1 logic ...
    } else {
        // do 2 logic ...
    }
}
```

Just make sure the users of such promise won't introduce [retain cycles](https://github.com/google/promises/blob/master/g3doc/index.md#ownership-and-retain-cycles) with something like:

```swift
object.connect().then { _ in
  object.doSomethingElse() 
  // object is now captured by the block which is captured by the promise returned from connect(), which in turn is owned by the object
  // although, the retain cycle will get broken once the promise gets resolved in either delegate call and nullified
}
```

Anyhow, checking the state of a promise with `isPending()` for logical branching is potentially error-prone, because the promise can get resolved on a background thread immediately after such check. Those methods are available for testing purposes only, so you need to `@testable import Promises` to get them.

**Comment by oxview** [comment]
Thank you for you advise and I am absolutely agree with ```checking the state of a promise with isPending() for logical branching is potentially error-prone``` I will rewrite my code. We can close this

**Pull request closed without merging**
