### PR TITLE
Rename await to awaitPromise

### PR DESCRIPTION
**Pull request by nsoojin**
Resolves https://github.com/google/promises/issues/167

Can you review? @shoumikhin Thank you

### CODE REVIEW

**Comment by alexanderkhitev** [comment]
Hello @shoumikhin ! Could you please review since Apple released a new version. Thank you!

**Review by alexanderkhitev — APPROVED** [review]

**Comment by ykjchen** [comment]
Thanks for the change. Do you mind also updating the documentation? (README.md, g3doc/index.md)

**Comment by nsoojin** [comment]
@ykjchen done

**Comment by ykjchen** [comment]
Thanks @nsoojin

**Comment by alexanderkhitev** [comment]
Hey @ykjchen ! Will you push a new release with these changes? Thank you!

**Comment by ykjchen** [comment]
Hey @alexanderkhitev, I'm working on it. I ran into some validation errors and hope to make time today to resolve them.

**Comment by alexanderkhitev** [comment]
> Hey @alexanderkhitev, I'm working on it. I ran into some validation errors and hope to make time today to resolve them.

Thanks!

**Comment by ykjchen** [comment]
Done now.

**Comment by alexanderkhitev** [comment]
@ykjchen Thank you! Could you please make a new release in the [repository](https://github.com/google/promises/releases)?

**Comment by alexanderkhitev** [comment]
Hey @ykjchen ! Could you please have a look on this [issue](https://github.com/google/promises/issues/173)? Thanks!

**Comment by ykjchen** [comment]
Hey @alexanderkhitev I didn't know about releases. Thanks for pointing it out. I created one. Does that issue #173?

**Comment by alexanderkhitev** [comment]
Hey @ykjchen ! Unfortunately this issue is still here. Maybe is it a reason `MLFPromisesSwift (1.2.8`)?

Please have a look

```
-> PromisesSwift (2.0.0)
   Synchronization construct for Swift
   pod 'PromisesSwift', '~> 2.0.0'
   - Homepage: https://github.com/google/promises
   - Source:   https://github.com/google/promises.git
   - Versions: 2.0.0, 1.2.12, 1.2.11, 1.2.10, 1.2.9, 1.2.8, 1.2.7, 1.2.6, 1.2.5,
   1.2.4, 1.2.3, 1.2.2, 1.2.1, 1.2, 1.1.1, 1.1.0, 1.0.8, 1.0.7, 1.0.6, 1.0.5,
   1.0.4, 1.0.3, 1.0.2 [cocoapods repo] - 1.2.12, 1.2.11, 1.2.10, 1.2.9, 1.2.8,
   1.2.7, 1.2.6, 1.2.5, 1.2.4, 1.2.3, 1.2.2, 1.2.1, 1.2, 1.1.1, 1.1.0, 1.0.8,
   1.0.7, 1.0.6, 1.0.5, 1.0.4, 1.0.3, 1.0.2 [cocoapods-main repo] - 1.2.12,
   1.2.11, 1.2.10, 1.2.9, 1.2.8, 1.2.7, 1.2.6, 1.2.5, 1.2.4, 1.2.3, 1.2.2,
   1.2.1, 1.2, 1.1.1, 1.1.0, 1.0.8, 1.0.7, 1.0.6, 1.0.5, 1.0.4, 1.0.3, 1.0.2
   [trunk repo]

-> MLFPromisesSwift (1.2.8)
   Synchronization construct for Swift
   pod 'MLFPromisesSwift', '~> 1.2.8'
   - Homepage: https://github.com/google/promises
   - Source:   https://github.com/google/promises.git
   - Versions: 1.2.8 [cocoapods repo] - 1.2.8 [cocoapods-main repo] - 1.2.8
   [trunk repo]
```

**Comment by ykjchen** [comment]
Does your project depend on MLFPromisesSwift? Is it possible to remove the dependency? If not it sounds like you'd need to get in touch with the maintainer of MLFPromisesSwift to update its dependency on PromisesSwift.

**Comment by alexanderkhitev** [comment]
Hey @ykjchen ! No, it doesn't depend on `MLFPromisesSwift`. I created a new project for testing Promises Framework install with this `Podfile`

```
use_modular_headers!

target 'Test-Promises' do
  pod 'PromisesSwift'
end
```
And CocoaPods installed this

```
Analyzing dependencies
Downloading dependencies
Installing PromisesObjC (1.2.12)
Installing PromisesSwift (1.2.12)
Generating Pods project
Integrating client project
```

Could you please try installing with a new project? I think you'll able to get the same result.

**Comment by alexanderkhitev** [comment]
Hey @ykjchen ! Now it installs 2.0.0 version, thank you!

**Pull request merged**
